server:
  port: 9600
spring:
  application:
    name: zuul-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    consumer-server-api:
      path: /bs/**
      serviceId: consumer-service-openfeign